# Generated by Django 4.1.6 on 2023-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.CharField(max_length=1200)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
